<script setup>
import axios from 'axios';
const superfanInvite = import.meta.env.VITE_SUPERFAN_INVITE
</script>

<template>
    <div class="content-container">
        <v-dialog v-model="loading" width="auto">
            <v-card max-width="400" prepend-icon="mdi-update"
                text="Please sit tight whilst we load in our spotify statistics" title="Fetching Spotify Data">
                <v-progress-circular color="primary" indeterminate style="margin: auto;"></v-progress-circular>
                <template v-slot:actions>
                    <v-btn class="ms-auto" text="Ok" @click="loading = false"></v-btn>
                </template>
            </v-card>
        </v-dialog>
        <div class="recipes-header header-font">
            Music
        </div>
        <div class="subtext">
            Keep up with what tunes and artists we've been loving recently
            <!-- <v-icon @click="() => openLink(superfanInvite)" icon="mdi-open-in-new" size="large"></v-icon> -->
            <v-tooltip v-model="showTooltip" location="top">
                <template v-slot:activator="{ props }">
                    <v-icon @click="() => openLink(superfanInvite)" icon="mdi-open-in-new" size="large"
                        v-bind="props"></v-icon>
                </template>
                <span>Click to join our superfan group!</span>
            </v-tooltip>
        </div>
        <div class="music-container">
            <div v-for="(user) in Object.keys(users)" :key="user" class="user-container">
                <div class="user-header ma-2 pa-2">{{ user }}</div>
                <!-- <div class="user-description">{{ users[user].description }}</div> -->
                <div class="d-flex justify-space-around mb-6 info-container">
                    <div class="d-flex flex-column mb-6 flex-grow-1">
                        <div class="ma-2 pa-2 info-header">Top Tracks</div>
                        <div v-for="track, index in users[user].trackData" :key="`${user}-track-${index}`"
                            class="individual-row d-flex">
                            <img :src="track.album.images[1].url" class="display-image"
                                @click="() => openLink(track['external_urls'].spotify)" style="cursor: pointer;" />
                            <span>
                                <div class="info-title">{{ track.name }}</div>
                                <div class="info-subtitle">{{ track.artists.slice(0, 3).map((artist) =>
            artist.name).join(", ")
                                    }}</div>
                            </span>
                        </div>
                    </div>
                    <div class="d-flex flex-column mb-6 flex-grow-1">
                        <div class="ma-2 pa-2 info-header">Top Artists</div>
                        <div v-for="artist, index in users[user].artistData" :key="`${user}-artist-${index}`"
                            class="individual-row d-flex">
                            <img :src="artist.images[1].url" class="display-image"
                                @click="() => openLink(artist['external_urls'].spotify)" style="cursor: pointer;" />
                            <span>
                                <div class="info-title">{{ artist.name }}</div>
                                <div class="info-subtitle">{{ artist.genres.slice(0, 3).join(", ") }}</div>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>

<script>
export default {
    name: 'Music Component',
    data() {
        return {
            users: {
                Harry: {
                    description: "This is a dummy description, to be generated by AI based on weekly songs and artists. Use large language model",
                    trackData: [],
                    artistData: []
                },
                Katie: {
                    description: "This is a dummy description, to be generated by AI based on weekly songs and artists. Use large language model",
                    trackData: [],
                    artistData: []
                }
            },
            showTooltip: false,
            loading: true,
        };
    },
    mounted() {
        this.fetchSpotifyData();
    },
    methods: {
        async fetchSpotifyData() {
            try {
                // Fetch Harry Spotify Data
                const backendUrl = import.meta.env.VITE_DB_HOST
                const spotifyResponse = await axios.get(`${backendUrl}/spotify_stats`);
                this.users['Harry'].trackData = spotifyResponse.data['harry']['track_data'].items;
                this.users['Harry'].artistData = spotifyResponse.data['harry']['artist_data'].items;
                this.users['Katie'].trackData = spotifyResponse.data['katie']['track_data'].items;
                this.users['Katie'].artistData = spotifyResponse.data['katie']['artist_data'].items;
                this.loading = false;
            } catch (err) {
                console.error('Error fetching data:', err);
            }
        },
        openLink(url) {
            window.open(url, '_blank');
        }
    }
}
</script>

<style>
.music-container {
    padding-top: 10px;
}

.user-container {
    margin: 40px 0px;
}

.user-header {
    font-size: 30px;
    font-weight: 800;
}

.user-description {
    font-size: 18px;
    font-weight: 400;
}

.info-container {
    background-color: #588157;
    color: white;
    border-radius: 10px;
}

.info-header {
    font-size: 25px;
    font-weight: 600;
    /* text-align: center; */
}

.info-title {
    font-size: 18px;
    font-weight: 400;
}

.info-subtitle {
    font-size: 15px;
    font-weight: 300;
}

.individual-row {
    margin: 10px 0px;
    padding: 0px 20px;
}

.display-image {
    width: 100px;
    height: 100px;
    margin-right: 10px;
}

.blue {
    background-color: blue;
}
</style>